export const fieldMap = {
  "X82t_awd_Qyc": "Administration, ekonomi, juridik",
  "j7Cq_ZJe_GkT": "Bygg och anläggning",
  "bh3H_Y3h_5eD": "Chefer och verksamhetsledare",
  "apaJ_2ja_LuF": "Data/IT",
  "RPTn_bxG_ExZ": "Försäljning, inköp, marknadsföring",
  "PaxQ_o1G_wWH": "Hantverksyrken",
  "ScKy_FHB_7wT": "Hotell, restaurang, storhushåll",
  "NYW6_mP6_vwf": "Hälso- och sjukvård",
  "wTEr_CBC_bqh": "Industriell tillverkning",
  "yhCP_AqT_tns": "Installation, drift, underhåll",
  "Uuf1_GMh_Uvw": "Kropps- och skönhetsvård",
  "9puE_nYg_crq": "Kultur, media, design",
  "bH5L_uXD_ZAX": "Militärt arbete",
  "VuuL_7CH_adj": "Naturbruk",
  "kJeN_wmw_9wX": "Naturvetenskapligt arbete",
  "MVqp_eS8_kDZ": "Pedagogiskt arbete",
  "whao_Q6A_ScE": "Sanering och renhållning",
  "GazW_2TU_kJw": "Socialt arbete",
  "E7hm_BLq_fqZ": "Säkerhetsarbete",
  "6Hq3_tKo_V57": "Tekniskt arbete",
  "ASGV_zcE_bWf": "Transport"
};

export const regionMap = {
  "DQZd_uYs_oKb": "Blekinge län",
  "oDpK_oZ2_WYt": "Dalarnas län",
  "K8iD_VQv_2BA": "Gotlands län",
  "zupA_8Nt_xcD": "Gävleborgs län",
  "wjee_qH2_yb6": "Hallands län",
  "65Ms_7r1_RTG": "Jämtlands län",
  "MtbE_xWT_eMi": "Jönköpings län",
  "9QUH_2bb_6Np": "Kalmar län",
  "tF3y_MF9_h5G": "Kronobergs län",
  "9hXe_F4g_eTG": "Norrbottens län",
  "CaRE_1nn_cSU": "Skåne län",
  "CifL_Rzy_Mku": "Stockholms län",
  "s93u_BEb_sx2": "Södermanlands län",
  "zBon_eET_fFU": "Uppsala län",
  "EVVp_h6U_GSZ": "Värmlands län",
  "g5Tt_CAV_zBd": "Västerbottens län",
  "NvUF_SP1_1zo": "Västernorrlands län",
  "G6DV_fKE_Viz": "Västmanlands län",
  "zdoY_6u5_Krt": "Västra Götalands län",
  "xTCk_nT5_Zjm": "Örebro län",
  "oLT3_Q9p_3nn": "Östergötlands län"
}; 